sudo: required
language: go
services:
- docker
go:
- 1.11.x
script:
- make test
- make package
- ls -alh java-buildpack-*.tgz
env:
  GO111MODULE: "on"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "java-buildpack-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
  on:
    tags: true
